[2025-07-25T09:55:56.706+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T09:55:56.751+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres2.load_user_dim_table manual__2025-07-25T09:55:49.900953+00:00 [queued]>
[2025-07-25T09:55:56.778+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres2.load_user_dim_table manual__2025-07-25T09:55:49.900953+00:00 [queued]>
[2025-07-25T09:55:56.780+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-25T09:55:56.809+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-25 09:55:49.900953+00:00
[2025-07-25T09:55:56.831+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=447) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T09:55:56.829+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres2', 'load_user_dim_table', 'manual__2025-07-25T09:55:49.900953+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpvnb08a50']
[2025-07-25T09:55:56.834+0000] {standard_task_runner.py:72} INFO - Started process 457 to run task
[2025-07-25T09:55:56.835+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask load_user_dim_table
[2025-07-25T09:55:57.006+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres2.load_user_dim_table manual__2025-07-25T09:55:49.900953+00:00 [running]> on host 72bd964f8e11
[2025-07-25T09:55:57.188+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres2' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T09:55:49.900953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T09:55:49.900953+00:00'
[2025-07-25T09:55:57.191+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-25T09:55:57.263+0000] {etl_dag.py:312} INFO - Loading user dimension table
[2025-07-25T09:55:57.270+0000] {etl_dag.py:332} INFO - Inserted 0 records into users table
[2025-07-25T09:55:57.271+0000] {etl_dag.py:335} INFO - User dimension table loaded successfully
[2025-07-25T09:55:57.272+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-25T09:55:57.695+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-25T09:55:57.699+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres2, task_id=load_user_dim_table, run_id=manual__2025-07-25T09:55:49.900953+00:00, execution_date=20250725T095549, start_date=20250725T095556, end_date=20250725T095557
[2025-07-25T09:55:57.782+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-25T09:55:57.815+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
