[2025-07-25T09:58:30.679+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T09:58:30.729+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres2.load_user_dim_table manual__2025-07-25T09:53:21.463693+00:00 [queued]>
[2025-07-25T09:58:30.760+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres2.load_user_dim_table manual__2025-07-25T09:53:21.463693+00:00 [queued]>
[2025-07-25T09:58:30.761+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-25T09:58:30.846+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-25 09:53:21.463693+00:00
[2025-07-25T09:58:30.878+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=600) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T09:58:30.882+0000] {standard_task_runner.py:72} INFO - Started process 616 to run task
[2025-07-25T09:58:30.871+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres2', 'load_user_dim_table', 'manual__2025-07-25T09:53:21.463693+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpg0m_jqqa']
[2025-07-25T09:58:30.885+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask load_user_dim_table
[2025-07-25T09:58:31.069+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres2.load_user_dim_table manual__2025-07-25T09:53:21.463693+00:00 [running]> on host 72bd964f8e11
[2025-07-25T09:58:31.318+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres2' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T09:53:21.463693+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T09:53:21.463693+00:00'
[2025-07-25T09:58:31.321+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-25T09:58:32.081+0000] {etl_dag.py:312} INFO - Loading user dimension table
[2025-07-25T09:58:32.087+0000] {etl_dag.py:332} INFO - Inserted 0 records into users table
[2025-07-25T09:58:32.088+0000] {etl_dag.py:335} INFO - User dimension table loaded successfully
[2025-07-25T09:58:32.089+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-25T09:58:32.127+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-25T09:58:32.129+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres2, task_id=load_user_dim_table, run_id=manual__2025-07-25T09:53:21.463693+00:00, execution_date=20250725T095321, start_date=20250725T095830, end_date=20250725T095832
[2025-07-25T09:58:32.261+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-25T09:58:32.346+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-25T09:58:32.358+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
