[2025-07-25T09:55:56.687+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T09:55:56.727+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres2.load_time_dim_table manual__2025-07-25T09:55:49.900953+00:00 [queued]>
[2025-07-25T09:55:56.754+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres2.load_time_dim_table manual__2025-07-25T09:55:49.900953+00:00 [queued]>
[2025-07-25T09:55:56.755+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-25T09:55:56.782+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_time_dim_table> on 2025-07-25 09:55:49.900953+00:00
[2025-07-25T09:55:56.799+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=450) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T09:55:56.798+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres2', 'load_time_dim_table', 'manual__2025-07-25T09:55:49.900953+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpjcejmemx']
[2025-07-25T09:55:56.804+0000] {standard_task_runner.py:72} INFO - Started process 451 to run task
[2025-07-25T09:55:56.804+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask load_time_dim_table
[2025-07-25T09:55:56.960+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres2.load_time_dim_table manual__2025-07-25T09:55:49.900953+00:00 [running]> on host 72bd964f8e11
[2025-07-25T09:55:57.145+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres2' AIRFLOW_CTX_TASK_ID='load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T09:55:49.900953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T09:55:49.900953+00:00'
[2025-07-25T09:55:57.148+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-25T09:55:57.212+0000] {etl_dag.py:436} INFO - Loading time dimension table
[2025-07-25T09:55:57.219+0000] {etl_dag.py:462} INFO - Inserted 0 records into time table
[2025-07-25T09:55:57.221+0000] {etl_dag.py:465} INFO - Time dimension table loaded successfully
[2025-07-25T09:55:57.222+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-25T09:55:57.653+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-25T09:55:57.655+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres2, task_id=load_time_dim_table, run_id=manual__2025-07-25T09:55:49.900953+00:00, execution_date=20250725T095549, start_date=20250725T095556, end_date=20250725T095557
[2025-07-25T09:55:57.746+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-25T09:55:57.813+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-25T09:55:57.821+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
