[2025-07-26T09:58:53.885+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-26T09:58:53.918+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_test2.load_user_dim_table manual__2025-07-26T09:48:29.655924+00:00 [queued]>
[2025-07-26T09:58:53.938+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_test2.load_user_dim_table manual__2025-07-26T09:48:29.655924+00:00 [queued]>
[2025-07-26T09:58:53.940+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 6
[2025-07-26T09:58:53.965+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-26 09:48:29.655924+00:00
[2025-07-26T09:58:53.982+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1142) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T09:58:53.985+0000] {standard_task_runner.py:72} INFO - Started process 1144 to run task
[2025-07-26T09:58:53.981+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres_test2', 'load_user_dim_table', 'manual__2025-07-26T09:48:29.655924+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmpn90vjop7']
[2025-07-26T09:58:53.986+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask load_user_dim_table
[2025-07-26T09:58:54.096+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_test2.load_user_dim_table manual__2025-07-26T09:48:29.655924+00:00 [running]> on host 2f3d4b2b9190
[2025-07-26T09:58:54.244+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres_test2' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T09:48:29.655924+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T09:48:29.655924+00:00'
[2025-07-26T09:58:54.246+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-26T09:58:54.283+0000] {my_dags.py:481} INFO - Loading user dimension table
[2025-07-26T09:58:54.300+0000] {my_dags.py:515} INFO - Inserted 96 records into users table
[2025-07-26T09:58:54.302+0000] {my_dags.py:523} INFO - No duplicate userids found
[2025-07-26T09:58:54.304+0000] {my_dags.py:526} INFO - User dimension table loaded successfully
[2025-07-26T09:58:54.305+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-26T09:58:54.321+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-26T09:58:54.322+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres_test2, task_id=load_user_dim_table, run_id=manual__2025-07-26T09:48:29.655924+00:00, execution_date=20250726T094829, start_date=20250726T095853, end_date=20250726T095854
[2025-07-26T09:58:54.363+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-26T09:58:54.420+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-26T09:58:54.424+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
