[2025-07-25T02:12:43.125+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T02:12:43.178+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres.load_user_dim_table manual__2025-07-25T02:12:33.272121+00:00 [queued]>
[2025-07-25T02:12:43.207+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres.load_user_dim_table manual__2025-07-25T02:12:33.272121+00:00 [queued]>
[2025-07-25T02:12:43.211+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-25T02:12:43.245+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-25 02:12:33.272121+00:00
[2025-07-25T02:12:43.282+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1422) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T02:12:43.287+0000] {standard_task_runner.py:72} INFO - Started process 1426 to run task
[2025-07-25T02:12:43.279+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres', 'load_user_dim_table', 'manual__2025-07-25T02:12:33.272121+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpcsdt0kvh']
[2025-07-25T02:12:43.289+0000] {standard_task_runner.py:105} INFO - Job 139: Subtask load_user_dim_table
[2025-07-25T02:12:43.538+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres.load_user_dim_table manual__2025-07-25T02:12:33.272121+00:00 [running]> on host 0c6a6447a272
[2025-07-25T02:12:44.539+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T02:12:33.272121+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T02:12:33.272121+00:00'
[2025-07-25T02:12:44.541+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-25T02:12:44.596+0000] {etl_dag.py:85} INFO - Loading user dimension table
[2025-07-25T02:12:44.609+0000] {etl_dag.py:100} INFO - Inserted 0 records into users table
[2025-07-25T02:12:44.611+0000] {etl_dag.py:103} INFO - User dimension table loaded successfully
[2025-07-25T02:12:44.613+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-25T02:12:44.647+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-25T02:12:44.654+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres, task_id=load_user_dim_table, run_id=manual__2025-07-25T02:12:33.272121+00:00, execution_date=20250725T021233, start_date=20250725T021243, end_date=20250725T021244
[2025-07-25T02:12:44.837+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-25T02:12:44.942+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
