[2025-07-26T09:55:12.307+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-26T09:55:12.339+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_test2.load_user_dim_table manual__2025-07-26T09:54:56.051938+00:00 [queued]>
[2025-07-26T09:55:12.354+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_test2.load_user_dim_table manual__2025-07-26T09:54:56.051938+00:00 [queued]>
[2025-07-26T09:55:12.355+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-26T09:55:12.374+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-26 09:54:56.051938+00:00
[2025-07-26T09:55:12.383+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=866) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T09:55:12.386+0000] {standard_task_runner.py:72} INFO - Started process 870 to run task
[2025-07-26T09:55:12.385+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres_test2', 'load_user_dim_table', 'manual__2025-07-26T09:54:56.051938+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmpqe_akhfv']
[2025-07-26T09:55:12.390+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask load_user_dim_table
[2025-07-26T09:55:12.497+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_test2.load_user_dim_table manual__2025-07-26T09:54:56.051938+00:00 [running]> on host 2f3d4b2b9190
[2025-07-26T09:55:12.683+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres_test2' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T09:54:56.051938+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T09:54:56.051938+00:00'
[2025-07-26T09:55:12.687+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-26T09:55:12.740+0000] {my_dags.py:486} INFO - Loading user dimension table
[2025-07-26T09:55:12.757+0000] {my_dags.py:523} INFO - Inserted 96 records into users table
[2025-07-26T09:55:12.758+0000] {my_dags.py:531} INFO - No duplicate userids found
[2025-07-26T09:55:12.761+0000] {my_dags.py:534} INFO - User dimension table loaded successfully
[2025-07-26T09:55:12.762+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-26T09:55:12.779+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-26T09:55:12.780+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres_test2, task_id=load_user_dim_table, run_id=manual__2025-07-26T09:54:56.051938+00:00, execution_date=20250726T095456, start_date=20250726T095512, end_date=20250726T095512
[2025-07-26T09:55:12.844+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-26T09:55:12.864+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
