[2025-07-25T02:12:43.233+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T02:12:43.306+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres.load_time_dim_table manual__2025-07-25T02:12:33.272121+00:00 [queued]>
[2025-07-25T02:12:43.354+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres.load_time_dim_table manual__2025-07-25T02:12:33.272121+00:00 [queued]>
[2025-07-25T02:12:43.356+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-25T02:12:43.441+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_time_dim_table> on 2025-07-25 02:12:33.272121+00:00
[2025-07-25T02:12:43.479+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1424) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T02:12:43.470+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres', 'load_time_dim_table', 'manual__2025-07-25T02:12:33.272121+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpqgfk8ybr']
[2025-07-25T02:12:43.483+0000] {standard_task_runner.py:72} INFO - Started process 1431 to run task
[2025-07-25T02:12:43.483+0000] {standard_task_runner.py:105} INFO - Job 142: Subtask load_time_dim_table
[2025-07-25T02:12:43.767+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres.load_time_dim_table manual__2025-07-25T02:12:33.272121+00:00 [running]> on host 0c6a6447a272
[2025-07-25T02:12:45.354+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres' AIRFLOW_CTX_TASK_ID='load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T02:12:33.272121+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T02:12:33.272121+00:00'
[2025-07-25T02:12:45.356+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-25T02:12:45.411+0000] {etl_dag.py:178} INFO - Loading time dimension table
[2025-07-25T02:12:45.418+0000] {etl_dag.py:193} INFO - Inserted 0 records into time table
[2025-07-25T02:12:45.419+0000] {etl_dag.py:196} INFO - Time dimension table loaded successfully
[2025-07-25T02:12:45.420+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-25T02:12:45.445+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-25T02:12:45.447+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres, task_id=load_time_dim_table, run_id=manual__2025-07-25T02:12:33.272121+00:00, execution_date=20250725T021233, start_date=20250725T021243, end_date=20250725T021245
[2025-07-25T02:12:45.520+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-25T02:12:45.609+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-25T02:12:45.614+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
